# Generated by Django 5.1.1 on 2025-01-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_watchlater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlater',
            name='user',
        ),
        migrations.DeleteModel(
            name='MovieRating',
        ),
        migrations.DeleteModel(
            name='WatchLater',
        ),
    ]
